services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      League\OAuth2\Server\Repositories\AccessTokenRepositoryInterface: '@R3H6\Oauth2Server\Domain\Repository\AccessTokenRepository'

  R3H6\Oauth2Server\:
    resource: '../Classes/*'

  R3H6\Oauth2Server\Hook\:
    resource: '../Classes/Hook/*'
    public: true

  R3H6\Oauth2Server\Controller\:
    resource: '../Classes/Controller/*'
    public: true

  R3H6\Oauth2Server\Domain\Configuration:
    public: true

  R3H6\Oauth2Server\Domain\Repository\ClientRepository:
    calls:
      - initializeObject: []

  R3H6\Oauth2Server\Domain\Repository\UserRepository:
    calls:
      - initializeObject: []

  League\OAuth2\Server\AuthorizationServer:
    factory: '@R3H6\Oauth2Server\Domain\Factory\AuthorizationServerFactory'

  League\OAuth2\Server\ResourceServer:
    factory: '@R3H6\Oauth2Server\Domain\Factory\ResourceServerFactory'
